### ISSUE TITLE
Trying to invoke protected method GraphQL\\Executor\\ReferenceExecutor::buildExecutionContext() from scope ReflectionMethod

### ISSUE THREAD

**Issue by AigarsMurins** [graycoreio/magento2-graphql-introspection-cache#7]
Hey

Installed the extension and ran a build on my PWA Studio project and received the following error:
`Trying to invoke protected method GraphQL\\Executor\\ReferenceExecutor::buildExecutionContext() from scope ReflectionMethod`

Issue happens in `\Graycore\GraphQlIntrospectionCache\Executor\ReferenceExecutor::create`
```
$reflectionMethod = new ReflectionMethod(\GraphQL\Executor\ReferenceExecutor::class, 'buildExecutionContext');
if ($reflectionMethod->isPrivate()) {
    $reflectionMethod->setAccessible(true);
}
```
I am on Magento 2.4.4-p1 and `webonyx/graphql-php` is at `v14.11.6`, and in this version `buildExecutionContext` is a `protected` method. Can you simply just add a check for `isProtected` here as well?

Thanks

**Comment by damienwebdev** [comment]
@AigarsMurins can you create a test that replicates this? I've just tested against v2.4.4-p2 and have no errors. https://github.com/graycoreio/magento2-graphql-introspection-cache/actions/runs/3256318832

**Comment by damienwebdev** [comment]
@AigarsMurins I'm going to close this as I never got a response or a replication.
